bash commands/local-detector_dfs_0_dfg_30.sh
bash commands/local-detector_dfs_0_dfg_33.sh
bash commands/local-detector_dfs_0_dfg_36.sh
bash commands/local-detector_dfs_0_dfg_40.sh
bash commands/local-detector_dfs_0_dfg_43.sh
bash commands/local-detector_dfs_0_dfg_46.sh
bash commands/local-detector_dfs_0_dfg_50.sh
bash commands/local-detector_dfs_2_dfg_30.sh
bash commands/local-detector_dfs_2_dfg_33.sh
bash commands/local-detector_dfs_2_dfg_36.sh
bash commands/local-detector_dfs_2_dfg_40.sh
bash commands/local-detector_dfs_2_dfg_43.sh
bash commands/local-detector_dfs_2_dfg_46.sh
bash commands/local-detector_dfs_2_dfg_50.sh
bash commands/local-detector_dfs_5_dfg_30.sh
bash commands/local-detector_dfs_5_dfg_33.sh
bash commands/local-detector_dfs_5_dfg_36.sh
bash commands/local-detector_dfs_5_dfg_40.sh
bash commands/local-detector_dfs_5_dfg_43.sh
bash commands/local-detector_dfs_5_dfg_46.sh
bash commands/local-detector_dfs_5_dfg_50.sh
bash commands/local-detector_dfs_7_dfg_30.sh
bash commands/local-detector_dfs_7_dfg_33.sh
bash commands/local-detector_dfs_7_dfg_36.sh
bash commands/local-detector_dfs_7_dfg_40.sh
bash commands/local-detector_dfs_7_dfg_43.sh
bash commands/local-detector_dfs_7_dfg_46.sh
bash commands/local-detector_dfs_7_dfg_50.sh
bash commands/local-detector_dfs_10_dfg_20.sh
bash commands/local-detector_dfs_10_dfg_30.sh
bash commands/local-detector_dfs_10_dfg_31.sh
bash commands/local-detector_dfs_10_dfg_33.sh
bash commands/local-detector_dfs_10_dfg_35.sh
bash commands/local-detector_dfs_10_dfg_36.sh
bash commands/local-detector_dfs_10_dfg_38.sh
bash commands/local-detector_dfs_10_dfg_40.sh
bash commands/local-detector_dfs_10_dfg_43.sh
bash commands/local-detector_dfs_10_dfg_46.sh
bash commands/local-detector_dfs_10_dfg_50.sh
bash commands/local-detector_dfs_12_dfg_30.sh
bash commands/local-detector_dfs_12_dfg_31.sh
bash commands/local-detector_dfs_12_dfg_33.sh
bash commands/local-detector_dfs_12_dfg_35.sh
bash commands/local-detector_dfs_12_dfg_36.sh
bash commands/local-detector_dfs_12_dfg_38.sh
bash commands/local-detector_dfs_12_dfg_40.sh
bash commands/local-detector_dfs_15_dfg_30.sh
bash commands/local-detector_dfs_15_dfg_31.sh
bash commands/local-detector_dfs_15_dfg_33.sh
bash commands/local-detector_dfs_15_dfg_35.sh
bash commands/local-detector_dfs_15_dfg_36.sh
bash commands/local-detector_dfs_15_dfg_38.sh
bash commands/local-detector_dfs_15_dfg_40.sh
bash commands/local-detector_dfs_17_dfg_30.sh
bash commands/local-detector_dfs_17_dfg_31.sh
bash commands/local-detector_dfs_17_dfg_33.sh
bash commands/local-detector_dfs_17_dfg_35.sh
bash commands/local-detector_dfs_17_dfg_36.sh
bash commands/local-detector_dfs_17_dfg_38.sh
bash commands/local-detector_dfs_17_dfg_40.sh
bash commands/local-detector_dfs_20_dfg_30.sh
bash commands/local-detector_dfs_20_dfg_31.sh
bash commands/local-detector_dfs_20_dfg_33.sh
bash commands/local-detector_dfs_20_dfg_35.sh
bash commands/local-detector_dfs_20_dfg_36.sh
bash commands/local-detector_dfs_20_dfg_38.sh
bash commands/local-detector_dfs_20_dfg_40.sh
bash commands/local-detector_dfs_22_dfg_30.sh
bash commands/local-detector_dfs_22_dfg_31.sh
bash commands/local-detector_dfs_22_dfg_33.sh
bash commands/local-detector_dfs_22_dfg_35.sh
bash commands/local-detector_dfs_22_dfg_36.sh
bash commands/local-detector_dfs_22_dfg_38.sh
bash commands/local-detector_dfs_22_dfg_40.sh
bash commands/local-detector_dfs_25_dfg_20.sh
bash commands/local-detector_dfs_25_dfg_30.sh
bash commands/local-detector_dfs_25_dfg_31.sh
bash commands/local-detector_dfs_25_dfg_33.sh
bash commands/local-detector_dfs_25_dfg_35.sh
bash commands/local-detector_dfs_25_dfg_36.sh
bash commands/local-detector_dfs_25_dfg_38.sh
bash commands/local-detector_dfs_25_dfg_40.sh
bash commands/local-detector_dfs_25_dfg_50.sh
bash commands/local-detector_dfs_30_dfg_30.sh
bash commands/local-detector_dfs_30_dfg_33.sh
bash commands/local-detector_dfs_30_dfg_36.sh
bash commands/local-detector_dfs_30_dfg_40.sh
bash commands/local-detector_dfs_40_dfg_20.sh
bash commands/local-detector_dfs_40_dfg_35.sh
bash commands/local-detector_dfs_40_dfg_50.sh
