sbatch commands/detector_x_40_z_-7.sh
sbatch commands/detector_x_40_z_-3.sh
sbatch commands/detector_x_40_z_0.sh
sbatch commands/detector_x_40_z_3.sh
sbatch commands/detector_x_40_z_6.sh
sbatch commands/detector_x_40_z_9.sh
sbatch commands/detector_x_40_z_13.sh
sbatch commands/detector_x_42_z_-7.sh
sbatch commands/detector_x_42_z_-3.sh
sbatch commands/detector_x_42_z_0.sh
sbatch commands/detector_x_42_z_3.sh
sbatch commands/detector_x_42_z_6.sh
sbatch commands/detector_x_42_z_9.sh
sbatch commands/detector_x_42_z_13.sh
sbatch commands/detector_x_45_z_-7.sh
sbatch commands/detector_x_45_z_-3.sh
sbatch commands/detector_x_45_z_0.sh
sbatch commands/detector_x_45_z_3.sh
sbatch commands/detector_x_45_z_6.sh
sbatch commands/detector_x_45_z_9.sh
sbatch commands/detector_x_45_z_13.sh
sbatch commands/detector_x_47_z_-7.sh
sbatch commands/detector_x_47_z_-3.sh
sbatch commands/detector_x_47_z_0.sh
sbatch commands/detector_x_47_z_3.sh
sbatch commands/detector_x_47_z_6.sh
sbatch commands/detector_x_47_z_9.sh
sbatch commands/detector_x_47_z_13.sh
sbatch commands/detector_x_50_z_-5.sh
sbatch commands/detector_x_50_z_1.sh
sbatch commands/detector_x_50_z_6.sh
sbatch commands/detector_x_50_z_9.sh
sbatch commands/detector_x_52_z_-5.sh
sbatch commands/detector_x_52_z_-2.sh
sbatch commands/detector_x_52_z_1.sh
sbatch commands/detector_x_55_z_-5.sh
sbatch commands/detector_x_55_z_-2.sh
sbatch commands/detector_x_55_z_1.sh
sbatch commands/detector_x_55_z_3.sh
sbatch commands/detector_x_57_z_-5.sh
sbatch commands/detector_x_57_z_-2.sh
sbatch commands/detector_x_57_z_1.sh
sbatch commands/detector_x_60_z_-5.sh
sbatch commands/detector_x_60_z_-2.sh
sbatch commands/detector_x_60_z_1.sh
sbatch commands/detector_x_62_z_-5.sh
sbatch commands/detector_x_62_z_-2.sh
sbatch commands/detector_x_62_z_1.sh
sbatch commands/detector_x_65_z_-5.sh
sbatch commands/detector_x_65_z_1.sh
